apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo2
spec:
  selector:
    matchLabels:
      app: podinfo2
  template:
    metadata:
      labels:
        app: podinfo2
    spec:
      containers:
        - name: podinfo2d
          image: ghcr.io/stefanprodan/podinfo:6.11.2 # {"$imagepolicy": "flux-system:podinfo"}
